[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
tui-textarea = "0.7.0"
